FROM golang:1.21-alpine3.18 as build

RUN addgroup -S myapp && adduser -S -u 10000 -g myapp myapp

WORKDIR /src
COPY go.mod go.sum ./

RUN go mod download

COPY . ./

RUN CGO_ENABLED=0 go build -o /app ./main.go

FROM scratch
LABEL maintainer="konrad.amtenbrink"

COPY --from=build /app /app
COPY --from=build /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
COPY --from=build /etc/passwd /etc/passwd

USER myapp
EXPOSE 8080

ENTRYPOINT ["app"]
