FROM golang:1.21-alpine3.18 as build

RUN apk add --no-cache git
RUN apk --no-cache add ca-certificates

RUN addgroup -S myapp && adduser -S -u 10000 -g myapp myapp

WORKDIR /src
COPY go.mod go.sum ./

RUN go mod download

COPY . ./

RUN CGO_ENABLED=0 go build -o /app ./main.go

FROM scratch
LABEL maintainer="konrad.amtenbrink"
COPY --from=build /app /app

COPY --from=build /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/

COPY --from=0 /etc/passwd /etc/passwd

USER myapp

ENTRYPOINT ["/app"]