FROM golang:1.21-alpine3.18 as build

WORKDIR /src
COPY go.mod go.sum ./

RUN go mod download

COPY . ./

RUN CGO_ENABLED=0 go build -o /app ./main.go

FROM gcr.io/distroless/static-debian12
LABEL maintainer="konrad.amtenbrink"

COPY --from=build --chown=nonroot:nonroot /app /app

USER nonroot:nonroot
EXPOSE 8080

ENTRYPOINT ["app"]
